name: Core Kernels LLIR Generator

on:
  pull_request:
    branches:
      - shared/gfx1250*
    paths:
      - 'third_party/amd/python/examples/gluon/*.py'
      - '.github/workflows/core_kernel_llir_gen.sh'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  gfx1250:
    name: gfx1250
    runs-on: ['self-hosted', 'ffm:mi450']

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}   # prevent merge
      - name: Set environment variables
        run: |
          COMMIT=$(git rev-parse --short=8 HEAD)
          RUN_ID=${{ github.run_id }}
          DIRNAME="commit-${COMMIT}-run-${RUN_ID}"
          echo "DIRNAME=${DIRNAME}" >> $GITHUB_ENV
      - name: Generating LLIR
        run: |
          set -xeo pipefail
          RENDER_GID=$(getent group render | cut -d: -f3)
          echo "Render group ID: ${RENDER_GID}"
          DIRNAME=${{ env.DIRNAME }}
          mkdir -p /data/ci/llir/${DIRNAME}
          docker run --rm --init \
            --name ci-core-llir-${{ github.run_id }} \
            --device=/dev/kfd --device=/dev/dri --group-add video --group-add $RENDER_GID \
            --cap-add=SYS_PTRACE --security-opt seccomp=unconfined \
            --shm-size=16G --ulimit memlock=-1 --ulimit stack=67108864 \
            -v /data/ci/actions-runner/_work/triton/triton:/code \
            -v /data/ci/llvm/7ec6f177-release:/llvm \
            -v /data/ci/ffm/rocdtif-7.12-am+ffmlite-mi400-r4.03:/ffm-base \
            -v /data/ci/ffm/ffmlite-master-20260520.152811:/ffm-update \
            -v /data/ci/triton-cache/json:/root/.triton/json \
            -v /data/ci/triton-cache/llvm:/root/.triton/llvm \
            -v /data/ci/triton-cache/nvidia:/root/.triton/nvidia \
            -v /data/ci/ccache:/root/.ccache \
            -v /data/ci/llir/${DIRNAME}:/llir \
            -w /code \
            --entrypoint bash \
            mkmhub.amd.com/sw-aiggfx1250-dev/ci/gfx1250-pytorch-env:1.4 \
            -lc "/code/.github/workflows/core_kernel_llir_gen.sh"
      - name: Cleanup
        if: always()
        run: |
          docker stop ci-core-llir-${{ github.run_id }} 2>/dev/null || true
          docker rm -f ci-core-llir-${{ github.run_id }} 2>/dev/null || true
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: core-llir-kernels-${{ env.DIRNAME }}
          path: /data/ci/llir/${{ env.DIRNAME }}/llir_kernels
          retention-days: 7
