name: roccap

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'CapFileName'
        required: true
        default: 'mxfp_fa_gfx1250_e4m3_e4m3_demo'
        type: string
      capFileRoot:
        description: 'CapFileRoot'
        required: true
        default: '/proj/triton_regr/TRITON/MXFP_FA/01011970/'
        type: string
      enableITrace:
        description: 'Enable ITrace'
        default: false
        type: boolean
      enableTTrace:
        description: 'Enable TTrace'
        default: false
        type: boolean
      kernelRegex:
        description: 'KernelRegex'
        required: true
        type: string
      dispatchNum:
        description: 'DispatchName'
        default: 0
        type: number
      groupName:
        description: 'GroupName'
        required: false
        default: 'CU_Tile_GEMM'
        type: string
      numXCCs:
        description: 'Number of XCCS(1 or 8)'
        required: true
        default: 1
        type: number
      cmd:
        description: 'Command'
        required: true
        type: string

permissions:
  contents: read

jobs:
  gfx1250:
    name: gfx1250
    runs-on: ['self-hosted', 'ffm', 'roccap']

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}   # prevent merge
      - name: Set environment variables
        run: |
          COMMIT=$(git rev-parse --short=8 HEAD)
          RUN_ID=${{ github.run_id }}
          DIRNAME="commit-${COMMIT}-run-${RUN_ID}"
          echo "DIRNAME=${DIRNAME}" >> $GITHUB_ENV
      - name: Invoke roccap
        run: |
          set -xeo pipefail
          RENDER_GID=$(getent group render | cut -d: -f3)
          echo "Render group ID: ${RENDER_GID}"
          DIRNAME=${{ env.DIRNAME }}
          mkdir /data/ci/roccap/${DIRNAME}
          docker run --rm --init \
            --name ci-roccap-${{ github.run_id }} \
            --device=/dev/kfd --device=/dev/dri --group-add video --group-add $RENDER_GID \
            --cap-add=SYS_PTRACE --security-opt seccomp=unconfined \
            --shm-size=16G --ulimit memlock=-1 --ulimit stack=67108864 \
            -v /data/ci/actions-runner/_work/triton/triton:/code \
            -v /data/ci/llvm/7ec6f177-release:/llvm \
            -v /data/ci/ffm/rocdtif-7.12-am+ffmlite-mi400-r4.03:/ffm-base \
            -v /data/ci/ffm/rocdtif-7.12-am+ffmlite-mi400-r4.03:/ffm-update \
            -v /data/ci/triton-cache/json:/root/.triton/json \
            -v /data/ci/triton-cache/llvm:/root/.triton/llvm \
            -v /data/ci/triton-cache/nvidia:/root/.triton/nvidia \
            -v /data/ci/ccache:/root/.ccache \
            -v /data/ci/roccap/${DIRNAME}:/roccap \
            -e ROCCAP_NAME=${ROCCAP_NAME} \
            -e ROCCAP_CAPFILE_ROOT=${ROCCAP_CAPFILE_ROOT} \
            -e ROCCAP_ENABLE_ITRACE=${ROCCAP_ENABLE_ITRACE} \
            -e ROCCAP_ENABLE_TTRACE=${ROCCAP_ENABLE_TTRACE} \
            -e ROCCAP_KERNEL_REGEX="${ROCCAP_KERNEL_REGEX}" \
            -e ROCCAP_DISPATCH_NUM=${ROCCAP_DISPATCH_NUM} \
            -e ROCCAP_GROUP_NAME=${ROCCAP_GROUP_NAME} \
            -e ROCCAP_NUM_XCC=${ROCCAP_NUM_XCC} \
            -w /code \
            --entrypoint bash \
            mkmhub.amd.com/sw-aiggfx1250-dev/ci/gfx1250-roccap:1.3 \
            -lc "/code/.github/workflows/roccap.sh ${ROCCAP_CMD}"
          cd /data/ci/roccap && tar -czvf triton-roccap-${DIRNAME}.tgz ${DIRNAME}
        env:
          ROCCAP_NAME: ${{ inputs.name }}
          ROCCAP_CAPFILE_ROOT: ${{ inputs.capFileRoot }}
          ROCCAP_ENABLE_ITRACE: ${{ inputs.enableITrace }}
          ROCCAP_ENABLE_TTRACE: ${{ inputs.enableTTrace }}
          ROCCAP_KERNEL_REGEX: ${{ inputs.kernelRegex }}
          ROCCAP_DISPATCH_NUM: ${{ inputs.dispatchNum }}
          ROCCAP_GROUP_NAME: ${{ inputs.groupName }}
          ROCCAP_NUM_XCC: ${{ inputs.numXCCs }}
          ROCCAP_CMD: ${{ inputs.cmd }}
      - name: Cleanup
        if: always()
        run: |
          docker stop ci-roccap-${{ github.run_id }} 2>/dev/null || true
          docker rm -f ci-roccap-${{ github.run_id }} 2>/dev/null || true
      - name: Upload artifact
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: triton-roccap-${{ env.DIRNAME }}
          path: /data/ci/roccap/${{ env.DIRNAME }}
          retention-days: 7
